name: Publish

on:
  repository_dispatch:
    types:
      - publish

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Check out code base
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Update Manifest
        shell: bash
        run: ./releaser

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@5f6978faf089d4d20b00c7766989d076bb2fc7f1 # v8.1.1
        with:
          add-paths: 'org.eu.wabarc.wayback.*'
          commit-message: 'Publish ${{ github.event.client_payload.version }}'
          branch: 'release/${{ github.event.client_payload.version }}'
          title: 'Publish ${{ github.event.client_payload.version }}'
          body: >
            **The maintainer will need to manually create a pull request to the upstream repository [flathub/org.eu.wabarc.wayback](https://github.com/flathub/org.eu.wabarc.wayback/compare/master...wabarc:org.eu.wabarc.wayback:master?expand=1).**
